# Generated by Django 5.0.14 on 2026-04-19 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropscan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Crop Scan', 'verbose_name_plural': 'Crop Scans'},
        ),
        migrations.AddField(
            model_name='cropscan',
            name='confidence',
            field=models.FloatField(default=0.0, help_text='AI confidence score (0-100)'),
        ),
        migrations.AddField(
            model_name='cropscan',
            name='fertilizer',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='cropscan',
            name='prevention',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cropscan',
            name='severity',
            field=models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='cropscan',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the scan (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cropscan',
            name='disease',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cropscan',
            name='image',
            field=models.ImageField(upload_to='scans/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='cropscan',
            name='pest',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cropscan',
            name='treatment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, default='', help_text='Session identifier for grouping conversations', max_length=100)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('message', models.TextField()),
                ('language', models.CharField(default='en', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
