# Generated by Django 5.0.14 on 2026-04-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cropscan_options_cropscan_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('plant_name', models.CharField(help_text='Primary affected plant/crop', max_length=200)),
                ('symptoms', models.JSONField(default=list, help_text='List of symptom strings')),
                ('cause', models.TextField(blank=True, default='')),
                ('organic_treatment', models.JSONField(default=list, help_text='List of organic treatment options')),
                ('chemical_treatment', models.JSONField(default=list, help_text='List of chemical treatment options')),
                ('dosage', models.TextField(blank=True, default='')),
                ('prevention', models.JSONField(default=list, help_text='List of prevention tips')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('watering_schedule', models.TextField(blank=True, default='')),
                ('fertilizer_plan', models.JSONField(default=list, help_text='Recommended fertilizers')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('organic', 'Organic'), ('chemical', 'Chemical'), ('mixed', 'Mixed')], default='chemical', max_length=20)),
                ('suitable_crops', models.JSONField(default=list, help_text='List of suitable crop names')),
                ('application_method', models.TextField(blank=True, default='')),
                ('dosage', models.TextField(blank=True, default='')),
                ('frequency', models.CharField(blank=True, default='', max_length=200)),
                ('benefits', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fertilizer',
                'verbose_name_plural': 'Fertilizers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('fungicide', 'Fungicide'), ('pesticide', 'Pesticide'), ('herbicide', 'Herbicide'), ('growth_regulator', 'Growth Regulator'), ('bactericide', 'Bactericide')], default='fungicide', max_length=20)),
                ('target_diseases', models.JSONField(default=list, help_text='Diseases this medicine treats')),
                ('target_pests', models.JSONField(default=list, help_text='Pests this medicine controls')),
                ('dosage', models.TextField(blank=True, default='')),
                ('application_method', models.TextField(blank=True, default='')),
                ('safety_period', models.CharField(blank=True, default='', help_text='Waiting period before harvest', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('scientific_name', models.CharField(blank=True, default='', max_length=200)),
                ('affected_crops', models.JSONField(default=list, help_text='List of affected crop names')),
                ('damage_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('control_methods', models.JSONField(default=list, help_text='Control/treatment methods')),
                ('prevention', models.JSONField(default=list, help_text='Prevention tips')),
                ('identification_features', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pest',
                'verbose_name_plural': 'Pests',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cropscan',
            name='card_title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='cropscan',
            name='cause',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cropscan',
            name='chemical_treatment',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cropscan',
            name='database_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cropscan',
            name='dosage',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cropscan',
            name='fertilizer_plan',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cropscan',
            name='medicine_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cropscan',
            name='organic_treatment',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cropscan',
            name='pest_control',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cropscan',
            name='plant_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cropscan',
            name='severity_color',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', max_length=10),
        ),
        migrations.AddField(
            model_name='cropscan',
            name='short_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cropscan',
            name='symptoms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cropscan',
            name='watering_schedule',
            field=models.TextField(blank=True, default=''),
        ),
    ]
