"""
Seed agriculture database with diseases, pests, fertilizers, and medicines.
Usage: python manage.py seed_data
"""
from django.core.management.base import BaseCommand
from api.models import Disease, Pest, Fertilizer, Medicine


class Command(BaseCommand):
    help = 'Seed the agriculture knowledge base'

    def handle(self, *args, **options):
        self._seed_diseases()
        self._seed_pests()
        self._seed_fertilizers()
        self._seed_medicines()
        self.stdout.write(self.style.SUCCESS('Agriculture database seeded successfully!'))

    def _seed_diseases(self):
        diseases = [
            {"name":"Leaf Blight","plant_name":"Wheat","symptoms":["Brown spots on leaves","Yellowing edges","Wilting tips"],"cause":"Fungal infection (Bipolaris sorokiniana)","organic_treatment":["Neem oil spray 2%","Trichoderma bio-agent"],"chemical_treatment":["Mancozeb 75% WP at 2.5g/L","Propiconazole 25% EC at 1ml/L"],"dosage":"2.5g/L water, spray every 10 days for 3 weeks","prevention":["Crop rotation","Use resistant varieties HD-2967","Proper plant spacing","Avoid overhead irrigation"],"severity":"medium","watering_schedule":"Reduce irrigation frequency during treatment period","fertilizer_plan":["NPK 19-19-19","Potash supplement for immunity"]},
            {"name":"Yellow Rust","plant_name":"Wheat","symptoms":["Yellow-orange pustules on leaves","Stripe pattern along leaf veins","Premature leaf death"],"cause":"Fungal pathogen Puccinia striiformis","organic_treatment":["Sulfur dust application","Neem-based bio-fungicide"],"chemical_treatment":["Propiconazole 25% EC (Tilt) at 1ml/L","Tebuconazole 250 EC at 1ml/L"],"dosage":"1ml/L, apply immediately upon detection","prevention":["Use resistant varieties like HD-2967","Early sowing","Remove volunteer wheat plants","Monitor fields regularly"],"severity":"high","watering_schedule":"Normal irrigation but avoid wet foliage","fertilizer_plan":["Potash-rich fertilizer","Avoid excess nitrogen"]},
            {"name":"Powdery Mildew","plant_name":"Tomato","symptoms":["White powdery coating on leaves","Leaf curling","Stunted growth"],"cause":"Fungal infection (Erysiphe cichoracearum)","organic_treatment":["Baking soda spray (1 tbsp/gallon)","Milk spray (40% solution)","Neem oil"],"chemical_treatment":["Sulfur 80% WP at 3g/L","Carbendazim 50% WP at 1g/L"],"dosage":"3g/L water, spray weekly","prevention":["Good air circulation","Avoid overcrowding","Morning watering only","Remove infected leaves"],"severity":"medium","watering_schedule":"Water at base only, avoid wetting leaves","fertilizer_plan":["Balanced NPK 10-10-10","Calcium supplement"]},
            {"name":"Late Blight","plant_name":"Potato","symptoms":["Dark water-soaked lesions","White mold on leaf undersides","Rapid plant death"],"cause":"Oomycete pathogen Phytophthora infestans","organic_treatment":["Copper hydroxide spray","Bordeaux mixture"],"chemical_treatment":["Metalaxyl + Mancozeb at 2.5g/L","Cymoxanil 8% + Mancozeb 64% at 3g/L"],"dosage":"2.5g/L, spray every 7 days preventively","prevention":["Use certified disease-free seed","Hill soil properly","Destroy infected plant debris","Avoid overhead irrigation"],"severity":"high","watering_schedule":"Drip irrigation only, keep foliage dry","fertilizer_plan":["Phosphorus-rich fertilizer","Potash for disease resistance"]},
            {"name":"Bacterial Wilt","plant_name":"Tomato","symptoms":["Sudden wilting without yellowing","Brown vascular tissue","Bacterial ooze from cut stems"],"cause":"Ralstonia solanacearum bacterium","organic_treatment":["Soil solarization","Bio-control with Pseudomonas fluorescens"],"chemical_treatment":["Streptocycline at 0.5g/L","Copper oxychloride 50% WP at 3g/L"],"dosage":"Drench soil with solution at 2L per plant","prevention":["Crop rotation with non-solanaceous crops","Use resistant rootstock","Improve soil drainage","Avoid injury to roots"],"severity":"high","watering_schedule":"Reduce watering, improve drainage","fertilizer_plan":["Calcium nitrate","Balanced micronutrients"]},
            {"name":"Brown Spot","plant_name":"Rice","symptoms":["Oval brown spots on leaves","Dark brown margins","Grain discoloration"],"cause":"Fungal infection (Bipolaris oryzae)","organic_treatment":["Pseudomonas fluorescens spray","Trichoderma soil treatment"],"chemical_treatment":["Mancozeb 75% WP at 2.5g/L","Carbendazim 50% WP at 1g/L"],"dosage":"2.5g/L, two sprays at 10-day intervals","prevention":["Balanced fertilization","Seed treatment with Carbendazim","Proper water management","Remove crop debris"],"severity":"medium","watering_schedule":"Maintain 2-3cm standing water during treatment","fertilizer_plan":["NPK 20-10-10","Zinc sulfate supplement"]},
            {"name":"Downy Mildew","plant_name":"Grape","symptoms":["Yellow oily spots on upper leaf","White downy growth underneath","Berry shriveling"],"cause":"Oomycete Plasmopara viticola","organic_treatment":["Copper-based sprays","Bordeaux mixture 1%"],"chemical_treatment":["Metalaxyl-M + Mancozeb at 2g/L","Fosetyl-Al at 3g/L"],"dosage":"2g/L preventive spray every 14 days","prevention":["Prune for air circulation","Remove fallen leaves","Use resistant cultivars","Avoid overhead watering"],"severity":"medium","watering_schedule":"Drip irrigation, avoid wetting canopy","fertilizer_plan":["Potassium-rich fertilizer","Foliar micronutrient spray"]},
            {"name":"Anthracnose","plant_name":"Mango","symptoms":["Black sunken lesions on fruits","Twig dieback","Flower blight"],"cause":"Fungal pathogen Colletotrichum gloeosporioides","organic_treatment":["Bordeaux mixture spray","Bio-agent Trichoderma viride"],"chemical_treatment":["Carbendazim 50% WP at 1g/L","Thiophanate-methyl at 1.5g/L"],"dosage":"1g/L, spray at flowering and fruit-set stages","prevention":["Prune dead branches","Collect fallen fruits","Pre-harvest spray schedule","Post-harvest hot water treatment"],"severity":"medium","watering_schedule":"Regular but avoid fruit wetting","fertilizer_plan":["NPK 10-26-26","Boron and zinc foliar spray"]},
            {"name":"Fusarium Wilt","plant_name":"Banana","symptoms":["Yellowing of older leaves","Splitting of pseudostem base","Vascular browning"],"cause":"Soil-borne fungus Fusarium oxysporum f.sp. cubense","organic_treatment":["Trichoderma harzianum soil application","Bio-fumigation with mustard"],"chemical_treatment":["Carbendazim soil drench at 2g/L","No fully effective chemical control"],"dosage":"Soil drench 2-3L per plant, repeat monthly","prevention":["Use tissue culture plants","Crop rotation","Raise field drainage","Avoid contaminated tools"],"severity":"high","watering_schedule":"Well-drained irrigation, no waterlogging","fertilizer_plan":["Neem cake","Potash-heavy fertilization"]},
            {"name":"Cercospora Leaf Spot","plant_name":"Soybean","symptoms":["Small angular reddish-brown spots","Leaf yellowing","Premature defoliation"],"cause":"Fungus Cercospora kikuchii","organic_treatment":["Neem oil foliar spray","Trichoderma-based bio-fungicide"],"chemical_treatment":["Carbendazim 50% WP at 1g/L","Hexaconazole 5% EC at 2ml/L"],"dosage":"1g/L, spray at pod-filling stage","prevention":["Use certified seed","Crop rotation","Remove crop residue","Maintain proper spacing"],"severity":"low","watering_schedule":"Normal irrigation schedule","fertilizer_plan":["Rhizobium inoculant","Single super phosphate"]},
            {"name":"Blast","plant_name":"Rice","symptoms":["Diamond-shaped spots on leaves","Neck rot","Panicle blast"],"cause":"Fungal pathogen Magnaporthe oryzae","organic_treatment":["Pseudomonas fluorescens","Tricyclazole seed treatment"],"chemical_treatment":["Tricyclazole 75% WP at 0.6g/L","Isoprothiolane 40% EC at 1.5ml/L"],"dosage":"0.6g/L at tillering and panicle initiation","prevention":["Use resistant varieties","Avoid excess nitrogen","Maintain proper water level","Silicon application"],"severity":"high","watering_schedule":"Alternate wetting and drying","fertilizer_plan":["Split nitrogen application","Silicon fertilizer"]},
            {"name":"Mosaic Virus","plant_name":"Tobacco","symptoms":["Mottled light and dark green patches","Leaf distortion","Stunted growth"],"cause":"Tobacco Mosaic Virus (TMV)","organic_treatment":["Remove infected plants","Milk spray as preventive (20%)"],"chemical_treatment":["No direct chemical cure","Control vector insects with Imidacloprid"],"dosage":"Imidacloprid 0.3ml/L for vector control","prevention":["Use virus-free seed","Wash hands before handling","Control aphid vectors","Disinfect tools with bleach"],"severity":"medium","watering_schedule":"Normal schedule, focus on vector control","fertilizer_plan":["Balanced NPK","Micronutrient foliar spray"]},
        ]
        count = 0
        for d in diseases:
            _, created = Disease.objects.update_or_create(name=d['name'], defaults=d)
            if created: count += 1
        self.stdout.write(f"  Diseases: {count} created, {len(diseases) - count} updated")

    def _seed_pests(self):
        pests = [
            {"name":"Aphids","scientific_name":"Aphis gossypii","affected_crops":["Cotton","Wheat","Mustard","Vegetables"],"damage_level":"medium","control_methods":["Neem oil spray 2%","Imidacloprid 17.8% SL at 0.5ml/L","Introduce ladybugs","Yellow sticky traps"],"prevention":["Companion planting with marigold","Avoid excess nitrogen","Regular field monitoring","Remove weed hosts"],"identification_features":"Small soft-bodied insects, green/black, found in colonies on tender shoots and leaf undersides"},
            {"name":"Whitefly","scientific_name":"Bemisia tabaci","affected_crops":["Cotton","Tomato","Okra","Chilli"],"damage_level":"high","control_methods":["Neem oil spray","Thiamethoxam 25% WG at 0.3g/L","Yellow sticky traps","Reflective mulches"],"prevention":["Intercropping with tall crops","Destroy crop residues","Use resistant varieties","Avoid continuous cropping"],"identification_features":"Tiny white moth-like insects on leaf undersides, cause sooty mold from honeydew"},
            {"name":"Stem Borer","scientific_name":"Scirpophaga incertulas","affected_crops":["Rice","Sugarcane","Maize"],"damage_level":"high","control_methods":["Trichogramma egg parasitoid release","Cartap hydrochloride 4G at 25kg/ha","Light traps","Clip affected tillers"],"prevention":["Early planting","Remove stubbles after harvest","Balanced nitrogen use","Use resistant varieties"],"identification_features":"Larvae bore into stems causing dead hearts in vegetative stage and white ears in reproductive stage"},
            {"name":"Army Worm","scientific_name":"Spodoptera frugiperda","affected_crops":["Maize","Sorghum","Rice","Sugarcane"],"damage_level":"high","control_methods":["Spray Emamectin benzoate 5% SG at 0.4g/L","Neem seed kernel extract 5%","Hand-picking in small fields","Pheromone traps"],"prevention":["Deep plowing","Bird perches in fields","Early sowing","Intercropping with legumes"],"identification_features":"Green-brown caterpillars with inverted Y on head, feed gregariously on leaves and whorl"},
            {"name":"Thrips","scientific_name":"Thrips tabaci","affected_crops":["Onion","Chilli","Cotton","Garlic"],"damage_level":"medium","control_methods":["Fipronil 5% SC at 1ml/L","Spinosad 45% SC at 0.3ml/L","Blue sticky traps","Neem oil"],"prevention":["Overhead irrigation to dislodge","Remove weed hosts","Crop rotation","Reflective mulch"],"identification_features":"Tiny slender insects causing silvery streaks on leaves, distortion of growing points"},
            {"name":"Red Cotton Bug","scientific_name":"Dysdercus koenigii","affected_crops":["Cotton","Okra"],"damage_level":"medium","control_methods":["Malathion 50% EC at 2ml/L","Neem kernel extract","Hand collection","Dust with Carbaryl 10%"],"prevention":["Timely picking of cotton","Destroy crop residues","Avoid late sowing","Clean cultivation"],"identification_features":"Bright red bugs with black markings, feed on cotton bolls causing staining of lint"},
            {"name":"Fruit Fly","scientific_name":"Bactrocera dorsalis","affected_crops":["Mango","Guava","Citrus","Cucumber"],"damage_level":"high","control_methods":["Methyl eugenol traps","Bait spray (Malathion + jaggery)","Neem oil","Collect fallen fruits"],"prevention":["Field sanitation","Harvest at proper maturity","Cold storage treatment","Pheromone traps"],"identification_features":"Medium-sized flies with yellow-brown body, larvae cause fruit rotting from inside"},
            {"name":"Jassids","scientific_name":"Amrasca biguttula","affected_crops":["Cotton","Okra","Brinjal"],"damage_level":"medium","control_methods":["Acetamiprid 20% SP at 0.2g/L","Neem oil spray","Dimethoate 30% EC at 1.5ml/L"],"prevention":["Hairy leaf varieties resist jassids","Proper spacing","Avoid excess nitrogen","Intercropping"],"identification_features":"Small wedge-shaped green insects causing leaf curling (hopper burn), feed on leaf undersides"},
            {"name":"Mealybug","scientific_name":"Phenacoccus solenopsis","affected_crops":["Cotton","Grapes","Papaya","Citrus"],"damage_level":"medium","control_methods":["Profenophos 50% EC at 2ml/L","Release Cryptolaemus beetle","Neem oil spray","Soap spray solution"],"prevention":["Destroy ant colonies that protect mealybugs","Remove alternate weed hosts","Quarantine infested material","Flood irrigation"],"identification_features":"White cottony masses on stems and leaf axils, produce honeydew causing sooty mold"},
            {"name":"Root Knot Nematode","scientific_name":"Meloidogyne incognita","affected_crops":["Tomato","Brinjal","Okra","Carrot"],"damage_level":"high","control_methods":["Carbofuran 3G at 1kg/ha","Paecilomyces lilacinus bio-agent","Neem cake at 250kg/ha","Soil solarization"],"prevention":["Crop rotation with cereals","Use resistant rootstock","Deep summer plowing","Marigold as trap crop"],"identification_features":"Cause root galls/swellings, stunted plant growth, yellowing of leaves, reduced yield"},
        ]
        count = 0
        for p in pests:
            _, created = Pest.objects.update_or_create(name=p['name'], defaults=p)
            if created: count += 1
        self.stdout.write(f"  Pests: {count} created, {len(pests) - count} updated")

    def _seed_fertilizers(self):
        fertilizers = [
            {"name":"NPK 19-19-19","type":"chemical","suitable_crops":["Wheat","Rice","Vegetables","Cotton","Maize"],"application_method":"Broadcast or fertigation. Dissolve in water for foliar spray.","dosage":"2-5 kg per acre depending on crop and soil test","frequency":"Every 2-3 weeks during active growth","benefits":"Balanced nutrition for overall plant growth, flowering, and fruiting"},
            {"name":"Urea (46-0-0)","type":"chemical","suitable_crops":["Wheat","Rice","Maize","Sugarcane","Cotton"],"application_method":"Top dressing or band placement. Split application recommended.","dosage":"50-100 kg per acre in 2-3 split doses","frequency":"At sowing, tillering, and panicle initiation","benefits":"Primary nitrogen source for vegetative growth and green color"},
            {"name":"DAP (18-46-0)","type":"chemical","suitable_crops":["Wheat","Rice","Potato","Soybean","Pulses"],"application_method":"Basal application at sowing. Place near root zone.","dosage":"50-75 kg per acre at sowing time","frequency":"Single basal dose at planting","benefits":"High phosphorus for root development, early vigor, and flowering"},
            {"name":"MOP (0-0-60)","type":"chemical","suitable_crops":["Potato","Banana","Tomato","Sugarcane","Fruit trees"],"application_method":"Broadcast and incorporate. Can split into 2 doses.","dosage":"30-50 kg per acre","frequency":"Basal + top dressing at flowering","benefits":"Potassium for disease resistance, fruit quality, and water regulation"},
            {"name":"Vermicompost","type":"organic","suitable_crops":["Wheat","Rice","Vegetables","Fruits","All crops"],"application_method":"Mix with soil before planting or apply as mulch around plants.","dosage":"1-2 tonnes per acre","frequency":"Once before each crop season","benefits":"Improves soil structure, water retention, beneficial microbes, slow-release nutrients"},
            {"name":"Neem Cake","type":"organic","suitable_crops":["Vegetables","Rice","Sugarcane","Fruit trees","Cotton"],"application_method":"Mix with soil. Acts as fertilizer and pest repellent.","dosage":"200-400 kg per acre","frequency":"Once at sowing/transplanting","benefits":"Natural pest deterrent, slow-release nitrogen, improves soil health"},
            {"name":"SSP (0-16-0)","type":"chemical","suitable_crops":["Wheat","Rice","Pulses","Oilseeds","Soybean"],"application_method":"Basal application. Best for sulfur-deficient soils.","dosage":"100-150 kg per acre","frequency":"Single basal application","benefits":"Phosphorus plus sulfur and calcium for root growth and nodulation in legumes"},
            {"name":"Bone Meal","type":"organic","suitable_crops":["Tomato","Potato","Roses","Fruit trees","Bulb crops"],"application_method":"Mix into soil at planting. Place in root zone.","dosage":"5-10 kg per 100 sq.ft","frequency":"Once at planting","benefits":"Slow-release phosphorus and calcium for strong roots and flowering"},
            {"name":"Zinc Sulfate","type":"chemical","suitable_crops":["Rice","Wheat","Maize","Soybean","Cotton"],"application_method":"Soil application or foliar spray (0.5% solution).","dosage":"10-25 kg per acre soil application, or 2g/L foliar","frequency":"Once per season soil, 2-3 foliar sprays","benefits":"Corrects zinc deficiency, improves grain quality and disease resistance"},
            {"name":"Seaweed Extract","type":"organic","suitable_crops":["Vegetables","Fruits","Cotton","Wheat","Rice"],"application_method":"Foliar spray or soil drench. Dilute as per product label.","dosage":"2-3 ml/L water for foliar spray","frequency":"Every 15-20 days","benefits":"Growth hormones, trace minerals, stress tolerance, improved root development"},
        ]
        count = 0
        for f in fertilizers:
            _, created = Fertilizer.objects.update_or_create(name=f['name'], defaults=f)
            if created: count += 1
        self.stdout.write(f"  Fertilizers: {count} created, {len(fertilizers) - count} updated")

    def _seed_medicines(self):
        medicines = [
            {"name":"Mancozeb 75% WP","type":"fungicide","target_diseases":["Leaf Blight","Late Blight","Downy Mildew","Brown Spot","Anthracnose"],"target_pests":[],"dosage":"2-2.5g per liter of water","application_method":"Foliar spray using knapsack sprayer. Ensure full coverage of leaves.","safety_period":"15-20 days before harvest"},
            {"name":"Carbendazim 50% WP","type":"fungicide","target_diseases":["Powdery Mildew","Anthracnose","Fusarium Wilt","Brown Spot","Blast"],"target_pests":[],"dosage":"1g per liter of water","application_method":"Foliar spray or seed treatment (2g/kg seed). Systemic action.","safety_period":"14 days before harvest"},
            {"name":"Propiconazole 25% EC","type":"fungicide","target_diseases":["Yellow Rust","Leaf Blight","Powdery Mildew","Sheath Blight"],"target_pests":[],"dosage":"1ml per liter of water","application_method":"Foliar spray. Systemic triazole fungicide.","safety_period":"21 days before harvest"},
            {"name":"Imidacloprid 17.8% SL","type":"pesticide","target_diseases":[],"target_pests":["Aphids","Whitefly","Jassids","Thrips","Termites"],"dosage":"0.3-0.5ml per liter of water","application_method":"Foliar spray or seed treatment. Systemic neonicotinoid.","safety_period":"14 days before harvest"},
            {"name":"Thiamethoxam 25% WG","type":"pesticide","target_diseases":[],"target_pests":["Whitefly","Aphids","Jassids","Brown Plant Hopper"],"dosage":"0.3g per liter of water","application_method":"Foliar spray or soil drench. Second-gen neonicotinoid.","safety_period":"14 days before harvest"},
            {"name":"Emamectin Benzoate 5% SG","type":"pesticide","target_diseases":[],"target_pests":["Army Worm","Stem Borer","Fruit Borer","Diamondback Moth"],"dosage":"0.4g per liter of water","application_method":"Foliar spray targeting larvae. Best applied in evening.","safety_period":"7 days before harvest"},
            {"name":"Copper Oxychloride 50% WP","type":"fungicide","target_diseases":["Bacterial Wilt","Late Blight","Downy Mildew","Canker"],"target_pests":[],"dosage":"2.5-3g per liter of water","application_method":"Foliar spray. Contact fungicide with bactericidal properties.","safety_period":"15 days before harvest"},
            {"name":"Tricyclazole 75% WP","type":"fungicide","target_diseases":["Blast","Neck Blast","Leaf Blast"],"target_pests":[],"dosage":"0.6g per liter of water","application_method":"Foliar spray at tillering and booting stage. Systemic action.","safety_period":"21 days before harvest"},
            {"name":"Chlorpyrifos 20% EC","type":"pesticide","target_diseases":[],"target_pests":["Stem Borer","Root Grubs","Termites","Cutworms"],"dosage":"2-2.5ml per liter of water","application_method":"Soil drench or foliar spray. Broad-spectrum organophosphate.","safety_period":"21 days before harvest"},
            {"name":"Gibberellic Acid (GA3)","type":"growth_regulator","target_diseases":[],"target_pests":[],"dosage":"10-50 ppm (0.01-0.05g/L)","application_method":"Foliar spray at specific growth stages. Promotes cell elongation.","safety_period":"No restriction"},
        ]
        count = 0
        for m in medicines:
            _, created = Medicine.objects.update_or_create(name=m['name'], defaults=m)
            if created: count += 1
        self.stdout.write(f"  Medicines: {count} created, {len(medicines) - count} updated")
